#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 10 21:27:00 2021

@author: sofiaribas
"""

import random

def fosf():
    n=21
    comando=input("Deseja ser o primeiro jogador? Sim ou Não")
    if comando=="Sim":
        while n>1:
            jogada=int(input("Quantos fosforos deseja retirar? 1,2,3,4"))
            if jogada >=1 and jogada<=4:
                n=n-jogada
                print("restam",n, "fosforos")
            if jogada==1:
                        n=n-4
                        print("O computador retira 4 fósforos.")
                        print("Restam", n, "fosforos!")
            if jogada==2:
                        n=n-3
                        print("O computador retira 3 fósforos.")
                        print("Restam", n, "fosforos!")
            if jogada==3:
                        n=n-2
                        print("O computador retira 2 fósforos.")
                        print("Restam", n, "fosforos!")    
            if jogada==4:
                        n=n-1
                        print("O computador retira 1 fósforos.")
                        print("Restam", n, "fosforos!")
            if jogada<1 or jogada>4:
                    print("Erro!")      
        print("Fim do jogo. Perdeu.")
        
    if comando=="Não":
            jogada_comp=random.randint(1,4)
            n=n-jogada_comp
            print("O computador retira", jogada_comp,"fosforos")
            print("restam",n, "fosforos")
            
            while n>1:
                jogada=int(input("Quantos fósforos retira? 1, 2, 3, 4"))
                if jogada>=1 and jogada<=4:    
                    n=n-jogada
                    print("Restam", n, "fosforos!")   
                    if n==1:
                        print("Jogador ganha")
                    if n==2:
                        jogada_comp=1
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                        print("O Jogador perdeu!")
                    if n==3:
                        jogada_comp=2
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                        print("O Jogador perdeu!")
                    if n==4:
                        jogada_comp=3
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                        print("O Jogador perdeu!")
                    if n==5:
                        jogada_comp=4
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                        print("O Jogador perdeu!")
                    if n==6:
                        jogada_comp=random.randint(1,4)
                        n=n-jogada_comp
                        print("O computador retirar", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==7:
                        jogada_comp=1
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==8:
                        jogada_comp=2
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==9:
                        jogada_comp=3
                        n=n-jogada_comp
                        print("O computador retirar", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==10:
                        jogada_comp=4
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==11:
                        jogada_comp=random.randint(1,4)
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==12:
                        jogada_comp=1
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==13:
                        jogada_comp=2
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==14:
                        jogada_comp=3
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==15:
                        jogada_comp=4
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==16:
                        jogada_comp=random.randint(1,4)
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==17:
                        jogada_comp=1
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==18:
                        jogada_comp=2
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==19:
                        jogada_comp=3
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                    if n==20:
                        jogada_comp=4
                        n=n-jogada_comp
                        print("O computador retira", jogada_comp, "fosforos.")
                        print("Restam", n, "fosforos!")
                if jogada<1 or jogada>4:
                    print("Erro!")
                    
                    
fosf()        
